eureka:
  instance:
    hostname: localhost
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
      
      
server:
  port: 3000
  
spring:
  application:
    name: employeeService1
    
     
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/hierarchyservice
    username: root
    password: Helloworld#9869
  
  jpa:
    hibernate:
      ddl-auto: create-drop
    database: mysql
    database-platform: org.hibernate.dialect.MySQLDialect    
    show-sql: true
    
  mvc:
    view:
      prefix: /jsps/
      
      suffix: .jsp  
