server:
  port: 8222
  
eureka:
  client:
    register-with-eureka: false
spring:
  application:
    name: gateway
    
    
spring.cloud.gateway.discovery.locator.enabled: true


spring.cloud.gateway.routes:        
        - id: employeeService1
          uri: http://localhost:3000
          predicates:
            - Path=/api/v1/employees/**
      
                 